### ISSUE TITLE
I have some questions about the dataset.

### ISSUE THREAD

**Issue by Tinkervic** [subbareddy248/WSNET#1]
May I ask if your dataset is publicly available, as I was unable to locate it on your Github?

**Comment by subbareddy248** [comment]
Hi,

We uploaded the wound images dataset. The corresponding masks will be uploaded it by tomorrow.

Thanks,
Subba

**Comment by subbareddy248** [comment]
Hi,

I hope you are doing well.

The mask images are uploaded on the same link.

Thanks,
Subba

**Comment by bc-bytes** [comment]
Many of the mask files do not have the same dimensions as the corresponding image files. All the image files are 331x331, but the masks are 331x331 or 224x224.
